// =============================================================================
// Economy Lab — interactive developer sandbox at /balance-report (see App.tsx).
//
// Runs client-side Monte Carlo simulations of the game's actual engine math in
// a Web Worker (scripts/simulate.worker.ts → src/sim/simCore.ts). Developers
// tweak GAX market constants, region gating, and worker speed live, pick a run
// count/length, and explore the results in three tabbed dashboards:
//   A — Market Behavior & GAX Health (volatility chart + significance swaps)
//   B — Regional Progression & Gate Bottlenecks (funnel + settlement volume)
//   C — Financial Performance & Bottleneck Diagnostics (vs hard-coded baseline)
// =============================================================================
import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import {
  DEFAULT_SIM_CONFIG, STRATEGY_ORDER, STRATEGY_LABEL, STRATEGY_DEFINITIONS,
  type LabReport, type SimConfig, type SimProgress, type StrategyName,
} from "./sim/simCore";
import type { WorkerReply } from "../scripts/simulate.worker";
import { ATTR_KEYS } from "./engine/potions";
import { ATTR_EMOJI, attrLabel } from "./engine/gax";
import { REGIONS } from "./data/regions";
import afterJson from "./data/after_run.json";
import { fmt } from "./util/format";

// ── Presentation constants ────────────────────────────────────────────────────
const STRAT_COLOR: Record<StrategyName, string> = {
  A_Sprinter: "#f59e0b", B_Completionist: "#22c55e",
  C_Industrialist: "#38bdf8", D_QuestHunter: "#a855f7",
  E_Achiever: "#f97316", F_Everyman: "#ec4899",
  G_Arbitrageur: "#14b8a6", H_GuildTrader: "#eab308",
};
const BASELINE_COLOR = "#64748b";
const ATTR_COLORS = [
  "#f59e0b", "#22c55e", "#38bdf8", "#a855f7", "#ec4899", "#14b8a6",
  "#f97316", "#eab308", "#84cc16", "#06b6d4", "#8b5cf6", "#f43f5e",
];

// Hard-coded baseline: the last committed default-parameter simulation
// (src/data/after_run.json, generated by scripts/simulate.ts). New archetypes
// have no legacy baseline and show as "new".
const BASELINE_KEY_MAP: Partial<Record<StrategyName, string>> = {
  A_Sprinter: "A_Sprinter", B_Completionist: "B_Completionist",
  C_Industrialist: "C_Industrialist", D_QuestHunter: "D_QuestHunter",
  E_Achiever: "E_AchievementHunter", F_Everyman: "F_Everyman",
};
const BASELINE_COINS: Partial<Record<StrategyName, number>> = {};
{
  const after = afterJson as unknown as { strategies?: Record<string, { summary_mean?: Record<string, number> }> };
  for (const s of STRATEGY_ORDER) {
    const key = BASELINE_KEY_MAP[s];
    const v = key ? after.strategies?.[key]?.summary_mean?.final_coins : undefined;
    if (v !== undefined) BASELINE_COINS[s] = v;
  }
}

function niceMax(v: number): number {
  if (v <= 0) return 1;
  const pow = Math.pow(10, Math.floor(Math.log10(v)));
  const n = v / pow;
  const step = n <= 1 ? 1 : n <= 2 ? 2 : n <= 5 ? 5 : 10;
  return step * pow;
}
const fmtMin = (min: number | null): string =>
  min === null ? "—" : min < 60 ? `${Math.round(min)}m` : `${(min / 60).toFixed(1)}h`;

// ── Backfill helpers ───────────────────────────────────────────────────────────
// The Lab only keeps results in React state — nothing persists between browser
// sessions. These two helpers are the hand-off path back to an analyst (human
// or Claude): either download the exact LabReport JSON that scripts/runLab.ts
// also produces, or copy the equivalent CLI invocation so the same config can
// be reproduced (and read straight off disk) without the browser at all.
function cliCommandFor(cfg: SimConfig): string {
  const flags = [
    `--gravityDecay=${cfg.gravityDecay}`,
    `--satCap=${cfg.satCap}`,
    `--healthyLimit=${cfg.healthyLimit}`,
    `--noiseAmplitude=${cfg.noiseAmplitude}`,
    `--regionCostMult=${cfg.regionCostMult}`,
    `--regionConstraints=${cfg.regionConstraintsEnabled}`,
    `--workerSpeedMult=${cfg.workerSpeedMult}`,
    `--travelTimeMult=${cfg.travelTimeMult}`,
    `--totalRuns=${cfg.totalRuns}`,
    `--simHours=${cfg.simHours}`,
  ];
  return `npx tsx scripts/runLab.ts ${flags.join(" ")}`;
}
function downloadJson(data: unknown, filename: string): void {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}

// ── Interactive line chart (tooltips + toggleable series + band) ──────────────
interface ChartSeries { label: string; color: string; points: number[]; dashed?: boolean; }
function HoverLineChart({
  title, xLabels, series, bandLo, bandHi, bandLabel, refValue, yFmt = fmt, yMin, height = 230,
}: {
  title: string;
  xLabels: number[];
  series: ChartSeries[];
  bandLo?: number[]; bandHi?: number[]; bandLabel?: string;
  refValue?: number;
  yFmt?: (n: number) => string;
  yMin?: number;
  height?: number;
}) {
  const [hidden, setHidden] = useState<Set<string>>(new Set());
  const [hover, setHover] = useState<number | null>(null);
  const svgRef = useRef<SVGSVGElement>(null);

  const W = 560, H = height, padL = 46, padR = 12, padT = 12, padB = 26;
  const innerW = W - padL - padR, innerH = H - padT - padB;
  const n = xLabels.length;
  const visible = series.filter((s) => !hidden.has(s.label));
  const allPts = [...visible.flatMap((s) => s.points), ...(bandHi ?? []), ...(refValue !== undefined ? [refValue] : [])];
  const lo = yMin !== undefined ? yMin : Math.min(0, ...allPts);
  const hi = Math.max(niceMax(Math.max(0.001, ...allPts)), lo + 0.001);
  const x = (i: number) => padL + (n <= 1 ? 0 : (i / (n - 1)) * innerW);
  const y = (v: number) => padT + innerH - ((Math.max(lo, Math.min(v, hi)) - lo) / (hi - lo)) * innerH;
  const toPath = (pts: number[]) =>
    pts.map((v, i) => `${i === 0 ? "M" : "L"}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" ");
  const gridY = [0, 0.25, 0.5, 0.75, 1].map((f) => lo + (hi - lo) * f);

  let bandPath = "";
  if (bandLo && bandHi && bandLo.length === n) {
    const top = bandHi.map((v, i) => `${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" L");
    const bottom = [...bandLo].reverse().map((v, i) => `${x(n - 1 - i).toFixed(1)},${y(v).toFixed(1)}`).join(" L");
    bandPath = `M ${top} L ${bottom} Z`;
  }

  const onMove = (e: React.MouseEvent<SVGSVGElement>) => {
    const rect = svgRef.current?.getBoundingClientRect();
    if (!rect || n < 2) return;
    const px = ((e.clientX - rect.left) / rect.width) * W;
    const i = Math.round(((px - padL) / innerW) * (n - 1));
    setHover(i >= 0 && i < n ? i : null);
  };

  return (
    <div className="relative rounded-xl border border-slate-700/70 bg-slate-900/50 p-3">
      <div className="mb-1 text-sm font-semibold text-slate-200">{title}</div>
      <svg ref={svgRef} viewBox={`0 0 ${W} ${H}`} className="w-full cursor-crosshair" role="img" aria-label={title}
        onMouseMove={onMove} onMouseLeave={() => setHover(null)}>
        {gridY.map((gv, i) => (
          <g key={i}>
            <line x1={padL} y1={y(gv)} x2={W - padR} y2={y(gv)} stroke="#334155" strokeWidth={i === 0 ? 1.2 : 0.6} />
            <text x={padL - 6} y={y(gv) + 3} textAnchor="end" fontSize="9" fill="#94a3b8">{yFmt(gv)}</text>
          </g>
        ))}
        {[0, Math.floor((n - 1) / 2), n - 1].filter((i) => i >= 0).map((i) => (
          <text key={i} x={x(i)} y={H - 8} textAnchor="middle" fontSize="9" fill="#94a3b8">{xLabels[i]}m</text>
        ))}
        {bandPath && <path d={bandPath} fill="#475569" fillOpacity={0.4} />}
        {refValue !== undefined && (
          <line x1={padL} y1={y(refValue)} x2={W - padR} y2={y(refValue)} stroke="#cbd5e1" strokeWidth={1} strokeDasharray="2 3" opacity={0.7} />
        )}
        {visible.map((s) => (
          <path key={s.label} d={toPath(s.points)} fill="none" stroke={s.color} strokeWidth={s.dashed ? 1.4 : 2}
            strokeDasharray={s.dashed ? "5 4" : undefined} strokeLinejoin="round" strokeLinecap="round" opacity={s.dashed ? 0.85 : 1} />
        ))}
        {hover !== null && hover < n && (
          <line x1={x(hover)} y1={padT} x2={x(hover)} y2={H - padB} stroke="#e2e8f0" strokeWidth={0.8} opacity={0.6} />
        )}
      </svg>
      {hover !== null && hover < n && (
        <div className="pointer-events-none absolute top-8 z-10 rounded-lg border border-slate-600 bg-slate-950/95 px-2.5 py-1.5 text-[11px] shadow-xl"
          style={{ left: `${8 + (hover / Math.max(1, n - 1)) * 70}%` }}>
          <div className="mb-0.5 font-semibold text-slate-300">t = {xLabels[hover]}m</div>
          {visible.map((s) => (
            <div key={s.label} className="flex items-center gap-1.5">
              <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ background: s.color }} />
              <span className="text-slate-400">{s.label}:</span>
              <span className="font-semibold text-slate-100">{yFmt(s.points[hover] ?? 0)}</span>
            </div>
          ))}
        </div>
      )}
      <div className="mt-1 flex flex-wrap gap-x-3 gap-y-0.5">
        {bandLo && (
          <span className="flex items-center gap-1.5 text-[10px] text-slate-400">
            <span className="inline-block h-3 w-3 rounded-sm bg-slate-600/70" />{bandLabel ?? "p10–p90"}
          </span>
        )}
        {series.map((s) => (
          <button key={s.label} onClick={() => setHidden((h) => { const nx = new Set(h); nx.has(s.label) ? nx.delete(s.label) : nx.add(s.label); return nx; })}
            className={`flex items-center gap-1.5 text-[10px] transition ${hidden.has(s.label) ? "text-slate-600 line-through" : "text-slate-300"}`}>
            <span className="inline-block h-0.5 w-4" style={{ background: hidden.has(s.label) ? "#475569" : s.color, borderTop: s.dashed ? `2px dashed ${s.color}` : undefined }} />
            {s.label}
          </button>
        ))}
      </div>
    </div>
  );
}

// ── Control panel atoms ───────────────────────────────────────────────────────
function SliderRow({ label, value, min, max, step, onChange, display }: {
  label: string; value: number; min: number; max: number; step: number;
  onChange: (v: number) => void; display?: (v: number) => string;
}) {
  return (
    <label className="block">
      <div className="mb-1 flex items-baseline justify-between text-xs">
        <span className="text-slate-300">{label}</span>
        <span className="font-mono font-semibold text-amber-300">{display ? display(value) : value}</span>
      </div>
      <input type="range" min={min} max={max} step={step} value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="w-full accent-amber-500" />
    </label>
  );
}
function NumberRow({ label, value, min, step, onChange }: {
  label: string; value: number; min: number; step: number; onChange: (v: number) => void;
}) {
  return (
    <label className="block">
      <div className="mb-1 text-xs text-slate-300">{label}</div>
      <input type="number" min={min} step={step} value={value}
        onChange={(e) => onChange(Math.max(min, Number(e.target.value) || min))}
        className="w-full rounded-lg border border-slate-700 bg-slate-950/60 px-2.5 py-1.5 text-sm font-semibold text-slate-100 outline-none focus:border-amber-500" />
    </label>
  );
}
function ToggleRow({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) {
  return (
    <button onClick={() => onChange(!value)} className="flex w-full items-center justify-between rounded-lg border border-slate-700 bg-slate-950/40 px-2.5 py-2 text-left">
      <span className="text-xs text-slate-300">{label}</span>
      <span className={`relative inline-block h-4 w-8 rounded-full transition ${value ? "bg-green-600" : "bg-slate-700"}`}>
        <span className={`absolute top-0.5 h-3 w-3 rounded-full bg-white transition-all ${value ? "left-4.5 translate-x-4" : "left-0.5"}`} style={{ left: value ? 18 : 2 }} />
      </span>
    </button>
  );
}
function SelectRow<T extends string | number>({ label, value, options, onChange }: {
  label: string; value: T; options: { v: T; label: string }[]; onChange: (v: T) => void;
}) {
  return (
    <label className="block">
      <div className="mb-1 text-xs text-slate-300">{label}</div>
      <select value={String(value)}
        onChange={(e) => { const opt = options.find((o) => String(o.v) === e.target.value); if (opt) onChange(opt.v); }}
        className="w-full rounded-lg border border-slate-700 bg-slate-950/60 px-2.5 py-1.5 text-sm font-semibold text-slate-100 outline-none focus:border-amber-500">
        {options.map((o) => <option key={String(o.v)} value={String(o.v)}>{o.label}</option>)}
      </select>
    </label>
  );
}
function PanelCard({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-4">
      <div className="mb-3 text-[11px] font-bold uppercase tracking-wider text-amber-400/90">{title}</div>
      <div className="space-y-3">{children}</div>
    </div>
  );
}

// ── Main view ─────────────────────────────────────────────────────────────────
type Tab = "market" | "regions" | "financial";

export default function BalanceReportView() {
  const [cfg, setCfg] = useState<SimConfig>({ ...DEFAULT_SIM_CONFIG });
  const [report, setReport] = useState<LabReport | null>(null);
  const [running, setRunning] = useState(false);
  const [progress, setProgress] = useState<SimProgress | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("market");
  const [marketStrat, setMarketStrat] = useState<StrategyName>("G_Arbitrageur");
  const [selectedAttrs, setSelectedAttrs] = useState<string[] | null>(null); // null = auto top-5
  const [selectedStrats, setSelectedStrats] = useState<Set<StrategyName>>(new Set(STRATEGY_ORDER));
  const [copied, setCopied] = useState(false);
  const workerRef = useRef<Worker | null>(null);
  const lastRunCfg = useRef<string | null>(null);

  const dirty = lastRunCfg.current !== JSON.stringify(cfg);
  const set = <K extends keyof SimConfig>(k: K, v: SimConfig[K]) => setCfg((c) => ({ ...c, [k]: v }));

  useEffect(() => () => workerRef.current?.terminate(), []);

  const run = () => {
    workerRef.current?.terminate();
    setError(null);
    setRunning(true);
    setProgress(null);
    const w = new Worker(new URL("../scripts/simulate.worker.ts", import.meta.url), { type: "module" });
    workerRef.current = w;
    w.onmessage = (e: MessageEvent<WorkerReply>) => {
      const msg = e.data;
      if (msg.type === "progress") setProgress(msg);
      else if (msg.type === "done") {
        setReport(msg.report);
        setRunning(false);
        lastRunCfg.current = JSON.stringify(cfg);
        w.terminate();
      } else if (msg.type === "error") {
        setError(msg.message);
        setRunning(false);
        w.terminate();
      }
    };
    w.onerror = (e) => { setError(e.message || "Worker crashed"); setRunning(false); };
    w.postMessage({ type: "run", config: cfg });
  };

  const activeStrats = STRATEGY_ORDER.filter((s) => selectedStrats.has(s) && report?.strategies[s]);

  // Auto attribute selection: the 5 most active (largest deviation from ×1.0).
  const autoAttrs = useMemo(() => {
    const rep = report?.strategies[marketStrat];
    if (!rep) return ATTR_KEYS.slice(0, 5) as string[];
    return [...ATTR_KEYS]
      .map((k) => ({ k, dev: Math.max(...rep.attr_series[k].mean.map((v) => Math.abs(v - 1))) }))
      .sort((a, b) => b.dev - a.dev)
      .slice(0, 5)
      .map((x) => x.k as string);
  }, [report, marketStrat]);
  const shownAttrs = selectedAttrs ?? autoAttrs;

  const marketRep = report?.strategies[marketStrat];

  return (
    <div className="h-full w-full overflow-y-auto bg-[#0b1120] text-slate-200">
      <div className="mx-auto max-w-6xl px-5 py-8">

        {/* ── Header ── */}
        <header className="mb-5 border-b border-slate-800 pb-4">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-amber-400/80">
            🧪 Idle Potion Brewer · Developer Sandbox
          </div>
          <h1 className="mt-1 text-3xl font-black text-white">Economy Lab &amp; Playthrough Simulator</h1>
          <p className="mt-2 max-w-3xl text-sm text-slate-400">
            Client-side Monte Carlo simulation of the game's <span className="font-semibold text-slate-200">exact engine math</span> —
            GAX market settling, regional unlock gates, settlement trades, potion mastery and bounties —
            across <span className="font-semibold text-slate-200">8 AI playstyles</span>. Tweak the levers, hit Run, and the
            simulation executes in a background Web Worker without freezing this tab.
          </p>
          <a href="/" className="mt-3 inline-block rounded-lg border border-slate-700 bg-slate-800/60 px-3 py-1.5 text-sm text-slate-300 hover:bg-slate-800">← Back to the workshop</a>
        </header>

        {/* ── Control panel ── */}
        <div className="grid gap-3 lg:grid-cols-3">
          <PanelCard title="A · Market Dynamics (GAX)">
            <SliderRow label="Hourly Gravity Decay Rate" value={cfg.gravityDecay} min={0.05} max={0.80} step={0.01}
              onChange={(v) => set("gravityDecay", v)} display={(v) => v.toFixed(2)} />
            <NumberRow label="Max Satiation Capacity (attr-points to ±50% cap)" value={cfg.satCap} min={100} step={100}
              onChange={(v) => set("satCap", v)} />
            <NumberRow label="Auto-Sale Absorption Limit (attr-points / market day)" value={cfg.healthyLimit} min={0} step={25}
              onChange={(v) => set("healthyLimit", v)} />
            <SliderRow label="Random Market Noise" value={cfg.noiseAmplitude} min={0} max={0.10} step={0.005}
              onChange={(v) => set("noiseAmplitude", v)} display={(v) => `${(v * 100).toFixed(1)}%`} />
          </PanelCard>

          <PanelCard title="B · Progression & World Tuning">
            <SliderRow label="Region Unlock Cost Multiplier" value={cfg.regionCostMult} min={0.5} max={3.0} step={0.1}
              onChange={(v) => set("regionCostMult", v)} display={(v) => `${v.toFixed(1)}×`} />
            <ToggleRow label="Regional hard constraints (discoveries / mastery / locations)"
              value={cfg.regionConstraintsEnabled} onChange={(v) => set("regionConstraintsEnabled", v)} />
            <SliderRow label="Worker Speed Multiplier" value={cfg.workerSpeedMult} min={0.5} max={2.0} step={0.05}
              onChange={(v) => set("workerSpeedMult", v)} display={(v) => `${v.toFixed(2)}×`} />
            <SliderRow label="Travel Time Multiplier" value={cfg.travelTimeMult} min={0.5} max={2.0} step={0.05}
              onChange={(v) => set("travelTimeMult", v)} display={(v) => `${v.toFixed(2)}×`} />
          </PanelCard>

          <PanelCard title="C · Simulation Runs">
            <SelectRow label="Simulations Count (total Monte Carlo runs)" value={cfg.totalRuns}
              options={[{ v: 50, label: "50 runs" }, { v: 100, label: "100 runs" }, { v: 300, label: "300 runs" }]}
              onChange={(v) => set("totalRuns", v)} />
            <SelectRow label="Simulation Length" value={cfg.simHours}
              options={[{ v: 24, label: "24 Hours (1s ticks)" }, { v: 168, label: "7 Days (5s ticks)" }, { v: 720, label: "30 Days (20s ticks)" }]}
              onChange={(v) => set("simHours", v)} />
            <button onClick={run} disabled={running}
              className={`w-full rounded-lg py-2.5 font-bold transition ${
                running ? "cursor-wait bg-slate-700 text-slate-400"
                : dirty ? "animate-pulse bg-green-600 text-white hover:bg-green-500"
                : "bg-green-700/70 text-white hover:bg-green-600"
              }`}>
              {running
                ? `Simulating… ${progress ? `${progress.pctComplete}% · ${STRATEGY_LABEL[progress.strategy]}` : "warming up"}`
                : dirty && report ? "▶ Run Simulation (parameters changed)" : "▶ Run Simulation"}
            </button>
            {running && (
              <div className="h-2 overflow-hidden rounded-full bg-slate-800">
                <div className="h-2 rounded-full bg-green-500 transition-all" style={{ width: `${progress?.pctComplete ?? 2}%` }} />
              </div>
            )}
            {error && <div className="rounded-lg border border-red-800 bg-red-950/40 p-2 text-xs text-red-300">{error}</div>}
            {report && !running && (
              <div className="space-y-2">
                <div className="text-[11px] text-slate-500">
                  Last run: {report.meta.total_runs} runs × {report.meta.sim_hours}h @ {report.meta.tick_seconds}s ticks
                  in {(report.meta.runtime_ms / 1000).toFixed(1)}s · {report.meta.content.ingredients} ingredients ·{" "}
                  {report.meta.content.locations} locations · {report.meta.content.settlements} settlements
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={() => downloadJson(report, `economy-lab-${new Date().toISOString().replace(/[:.]/g, "-")}.json`)}
                    className="flex-1 rounded-lg border border-slate-700 bg-slate-800/70 py-1.5 text-[11px] font-semibold text-slate-300 hover:bg-slate-800">
                    ⬇ Export Report JSON
                  </button>
                  <button
                    onClick={() => { navigator.clipboard.writeText(cliCommandFor(cfg)); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
                    className={`flex-1 rounded-lg border py-1.5 text-[11px] font-semibold transition ${copied ? "border-green-700 bg-green-900/40 text-green-300" : "border-slate-700 bg-slate-800/70 text-slate-300 hover:bg-slate-800"}`}>
                    {copied ? "✓ Copied" : "📋 Copy CLI Command"}
                  </button>
                </div>
                <p className="text-[10px] leading-relaxed text-slate-600">
                  Neither the browser tab nor this run survives a page reload. To hand results to Claude for balance analysis:
                  either send the exported JSON, or paste the CLI command into a terminal — it runs the identical simulation
                  headlessly via <code className="text-slate-500">scripts/runLab.ts</code> and writes to <code className="text-slate-500">sim-reports/</code>, which Claude can read directly.
                </p>
              </div>
            )}
          </PanelCard>
        </div>

        {/* ── Empty state ── */}
        {!report && !running && (
          <div className="mt-10 rounded-xl border border-dashed border-slate-700 bg-slate-900/30 p-10 text-center text-slate-400">
            <div className="text-4xl">⚗️</div>
            <div className="mt-2 font-semibold text-slate-300">No simulation yet</div>
            <div className="mt-1 text-sm">Tune the parameters above and press <span className="font-semibold text-green-400">Run Simulation</span> — results land here as three interactive dashboards.</div>
          </div>
        )}

        {report && (
          <>
            {/* ── Global flags ── */}
            {report.global.flags.length > 0 && (
              <div className="mt-4 rounded-xl border border-amber-700/60 bg-amber-950/30 p-3 text-sm">
                {report.global.flags.map((f) => (
                  <span key={f} className="mr-2 rounded bg-amber-900/60 px-2 py-0.5 text-[11px] font-bold text-amber-300">⚠ {f}</span>
                ))}
                <span className="text-amber-200/90">{report.global.notes[report.global.notes.length - 1]}</span>
              </div>
            )}

            {/* ── Strategy filter chips ── */}
            <div className="mt-5 flex flex-wrap items-center gap-1.5">
              <span className="mr-1 text-[11px] uppercase tracking-wider text-slate-500">Archetypes:</span>
              {STRATEGY_ORDER.map((s) => (
                <button key={s} title={STRATEGY_DEFINITIONS[s]}
                  onClick={() => setSelectedStrats((prev) => { const nx = new Set(prev); nx.has(s) ? nx.delete(s) : nx.add(s); return nx; })}
                  className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold transition ${
                    selectedStrats.has(s)
                      ? "border-transparent text-slate-950"
                      : "border-slate-700 bg-transparent text-slate-500"
                  }`}
                  style={selectedStrats.has(s) ? { background: STRAT_COLOR[s] } : undefined}>
                  {STRATEGY_LABEL[s]}
                </button>
              ))}
            </div>

            {/* ── Tabs ── */}
            <div className="mt-4 flex gap-1 border-b border-slate-800">
              {([
                ["market", "A · Market Behavior & GAX Health"],
                ["regions", "B · Regional Progression"],
                ["financial", "C · Financial Performance"],
              ] as [Tab, string][]).map(([t, label]) => (
                <button key={t} onClick={() => setTab(t)}
                  className={`rounded-t-lg px-4 py-2 text-sm font-semibold transition ${
                    tab === t ? "border border-b-0 border-slate-700 bg-slate-900 text-amber-300" : "text-slate-500 hover:text-slate-300"
                  }`}>
                  {label}
                </button>
              ))}
            </div>

            {/* ════ TAB A — Market Behavior & GAX Health ════ */}
            {tab === "market" && marketRep && (
              <div className="mt-4 space-y-4">
                <div className="flex flex-wrap items-center gap-3">
                  <label className="text-xs text-slate-400">
                    Market as experienced by{" "}
                    <select value={marketStrat} onChange={(e) => setMarketStrat(e.target.value as StrategyName)}
                      className="ml-1 rounded-lg border border-slate-700 bg-slate-950/60 px-2 py-1 text-sm font-semibold text-slate-100">
                      {STRATEGY_ORDER.map((s) => <option key={s} value={s}>{STRATEGY_LABEL[s]}</option>)}
                    </select>
                  </label>
                  <span className="text-[11px] text-slate-500">
                    avg sale multiplier ×{marketRep.summary_mean.gax_avg_sale_mult} · {fmt(marketRep.summary_mean.potions_sold)} potions sold/run
                  </span>
                </div>

                {/* Attribute chips */}
                <div className="flex flex-wrap gap-1">
                  {ATTR_KEYS.map((k) => {
                    const on = shownAttrs.includes(k);
                    return (
                      <button key={k}
                        onClick={() => {
                          const cur = selectedAttrs ?? autoAttrs;
                          const nx = on ? cur.filter((a) => a !== k) : [...cur, k].slice(-8);
                          setSelectedAttrs(nx);
                        }}
                        className={`rounded px-1.5 py-0.5 text-[10px] transition ${on ? "bg-slate-700 font-semibold text-amber-200" : "bg-slate-900 text-slate-500 hover:text-slate-300"}`}>
                        {ATTR_EMOJI[k]} {attrLabel(k)}
                      </button>
                    );
                  })}
                  <button onClick={() => setSelectedAttrs(null)} className="rounded px-1.5 py-0.5 text-[10px] text-sky-400 hover:text-sky-300">↺ auto (top 5 movers)</button>
                </div>

                <HoverLineChart
                  title={`Price multiplier over time — ${STRATEGY_LABEL[marketStrat]} (mean across runs; band = ${shownAttrs[0] ? attrLabel(shownAttrs[0]) : ""} p10–p90; dashed = standout run)`}
                  xLabels={marketRep.timeseries.t_minutes}
                  series={[
                    ...shownAttrs.map((k, i) => ({
                      label: attrLabel(k),
                      color: ATTR_COLORS[i % ATTR_COLORS.length],
                      points: marketRep.attr_series[k]?.mean ?? [],
                    })),
                    ...(marketRep.standout ? [{
                      label: marketRep.standout.label,
                      color: "#fde68a",
                      points: marketRep.standout.series,
                      dashed: true,
                    }] : []),
                  ]}
                  bandLo={shownAttrs[0] ? marketRep.attr_series[shownAttrs[0]]?.p10 : undefined}
                  bandHi={shownAttrs[0] ? marketRep.attr_series[shownAttrs[0]]?.p90 : undefined}
                  bandLabel={shownAttrs[0] ? `${attrLabel(shownAttrs[0])} p10–p90` : undefined}
                  refValue={1}
                  yFmt={(v) => `×${v.toFixed(2)}`}
                  yMin={0.4}
                  height={260}
                />
                <p className="text-xs text-slate-500">
                  <span className="font-semibold text-slate-400">Crash &amp; Recovery stress test:</span> healthy tuning keeps lines hovering
                  around the ×1.00 baseline with wavy organic movement. Flatlines pinned at ×0.50 mean satiation is locking the floor
                  (raise gravity or absorption); a dead-straight ×1.00 line means the market never engages at all.
                </p>

                {/* Significance swap log */}
                <div className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-4">
                  <div className="mb-2 text-sm font-semibold text-slate-200">Significance Swap Log — board evictions per run ({STRATEGY_LABEL[marketStrat]})</div>
                  {marketRep.evictions_mean.length === 0 ? (
                    <p className="text-xs text-slate-500">No attributes were kicked off the Top-10 board — the market stayed dormant. Push more sales volume or lower the absorption limit.</p>
                  ) : (
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="text-left text-[10px] uppercase tracking-wider text-slate-500">
                          <th className="py-1">Attribute</th><th className="py-1">Avg evictions / run</th><th className="py-1">Relative churn</th>
                        </tr>
                      </thead>
                      <tbody>
                        {marketRep.evictions_mean.map((e) => {
                          const max = marketRep.evictions_mean[0].count || 1;
                          return (
                            <tr key={e.attr} className="border-t border-slate-800/70">
                              <td className="py-1.5 font-semibold text-slate-200">{ATTR_EMOJI[e.attr]} {attrLabel(e.attr)}</td>
                              <td className="py-1.5">{e.count}</td>
                              <td className="py-1.5">
                                <div className="h-2.5 w-full max-w-56 rounded bg-slate-800">
                                  <div className="h-2.5 rounded bg-rose-500/80" style={{ width: `${(e.count / max) * 100}%` }} />
                                </div>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>
            )}

            {/* ════ TAB B — Regional Progression ════ */}
            {tab === "regions" && (
              <div className="mt-4 space-y-4">
                {/* Region unlock funnel */}
                <div className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-4">
                  <div className="mb-1 text-sm font-semibold text-slate-200">Region Unlock Funnel — mean time to break each gate</div>
                  <p className="mb-3 text-xs text-slate-500">Coins × {cfg.regionCostMult.toFixed(1)} {cfg.regionConstraintsEnabled ? "+ discovery/mastery/location constraints" : "(constraints disabled)"} · bar label shows % of runs that made it.</p>
                  <div className="space-y-3">
                    {REGIONS.slice(1).map((r) => {
                      const horizonMin = (report.meta.sim_hours ?? 24) * 60;
                      return (
                        <div key={r.id}>
                          <div className="mb-1 text-xs font-semibold text-slate-300">{r.name} <span className="font-normal text-slate-500">— {fmt(Math.round(r.unlockCost * cfg.regionCostMult))}🪙 · needs {r.constraints.potionsDiscovered} potions, {r.constraints.recipesMastered} mastered</span></div>
                          <div className="space-y-1">
                            {activeStrats.map((s) => {
                              const row = report.strategies[s].region_funnel.find((f) => f.regionId === r.id);
                              const min = row?.mean_unlock_min ?? null;
                              const pctRuns = row?.unlocked_pct ?? 0;
                              return (
                                <div key={s} className="flex items-center gap-2">
                                  <span className="w-28 shrink-0 truncate text-[10px]" style={{ color: STRAT_COLOR[s] }}>{STRATEGY_LABEL[s]}</span>
                                  <div className="h-3.5 flex-1 rounded bg-slate-800/70">
                                    {min !== null && (
                                      <div className="flex h-3.5 items-center rounded pl-1.5 text-[9px] font-bold text-slate-950"
                                        style={{ width: `${Math.min(100, Math.max(4, (min / horizonMin) * 100))}%`, background: STRAT_COLOR[s] }}>
                                        {fmtMin(min)}
                                      </div>
                                    )}
                                  </div>
                                  <span className="w-14 shrink-0 text-right text-[10px] text-slate-500">{min === null ? "never" : `${pctRuns}% runs`}</span>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Settlement prosperity progression */}
                <HoverLineChart
                  title="Average Settlement Prosperity Level over time (mean across all 10 towns, per archetype)"
                  xLabels={report.strategies[activeStrats[0] ?? "A_Sprinter"]?.timeseries.t_minutes ?? []}
                  series={activeStrats.map((s) => ({
                    label: STRATEGY_LABEL[s], color: STRAT_COLOR[s],
                    points: report.strategies[s].timeseries.settlement_lvl_mean ?? [],
                  }))}
                  yFmt={(v) => `L${v.toFixed(1)}`}
                  yMin={1}
                  height={210}
                />
                <p className="-mt-2 text-xs text-slate-500">
                  Every delivered item grants a town +1 Prosperity XP. Level 5 opens each town's bonus offer; level 10 grants
                  Barter Efficiency and the full ±15% regional Waypoint/Cargo passive. Flat lines at L1.0 mean an archetype never trades.
                </p>

                {/* Settlement trade volume */}
                <div className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-4">
                  <div className="mb-2 text-sm font-semibold text-slate-200">Settlement Trade Volume vs Standard Potion Sales (mean per run)</div>
                  <div className="space-y-1.5">
                    {activeStrats.map((s) => {
                      const m = report.strategies[s].summary_mean;
                      const maxV = Math.max(1, ...activeStrats.map((x) => Math.max(report.strategies[x].summary_mean.settlement_trades, report.strategies[x].summary_mean.potions_sold)));
                      return (
                        <div key={s} className="flex items-center gap-2">
                          <span className="w-28 shrink-0 truncate text-[10px]" style={{ color: STRAT_COLOR[s] }}>{STRATEGY_LABEL[s]}</span>
                          <div className="flex-1 space-y-0.5">
                            <div className="flex items-center gap-1.5">
                              <div className="h-2.5 rounded bg-amber-500/90" style={{ width: `${(m.settlement_trades / maxV) * 100}%`, minWidth: m.settlement_trades > 0 ? 4 : 0 }} />
                              <span className="text-[9px] text-amber-300">{fmt(m.settlement_trades)} trades</span>
                            </div>
                            <div className="flex items-center gap-1.5">
                              <div className="h-2.5 rounded bg-sky-500/80" style={{ width: `${(m.potions_sold / maxV) * 100}%`, minWidth: m.potions_sold > 0 ? 4 : 0 }} />
                              <span className="text-[9px] text-sky-300">{fmt(m.potions_sold)} potions sold</span>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {/* ════ TAB C — Financial Performance ════ */}
            {tab === "financial" && (
              <div className="mt-4 space-y-4">
                {/* Final coins vs baseline */}
                <div className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-4">
                  <div className="mb-1 text-sm font-semibold text-slate-200">Final Coins — this run vs hard-coded baseline</div>
                  <p className="mb-3 text-xs text-slate-500">Grey = committed baseline (data/after_run.json, default parameters). Colored = this simulation. New archetypes have no baseline yet.</p>
                  <div className="space-y-1.5">
                    {activeStrats.map((s) => {
                      const cur = report.strategies[s].summary_mean.final_coins;
                      const base = BASELINE_COINS[s];
                      const maxV = Math.max(1, ...activeStrats.flatMap((x) => [report.strategies[x].summary_mean.final_coins, BASELINE_COINS[x] ?? 0]));
                      const p10 = report.strategies[s].final_coins_p10, p90 = report.strategies[s].final_coins_p90;
                      return (
                        <div key={s} className="flex items-center gap-2">
                          <span className="w-28 shrink-0 truncate text-[10px]" style={{ color: STRAT_COLOR[s] }} title={STRATEGY_DEFINITIONS[s]}>{STRATEGY_LABEL[s]}</span>
                          <div className="flex-1 space-y-0.5">
                            <div className="flex items-center gap-1.5">
                              <div className="h-2.5 rounded" style={{ width: `${(cur / maxV) * 100}%`, minWidth: 4, background: STRAT_COLOR[s] }} />
                              <span className="text-[9px] font-semibold text-slate-200">{fmt(cur)} <span className="font-normal text-slate-500">(p10 {fmt(p10)} / p90 {fmt(p90)})</span></span>
                            </div>
                            <div className="flex items-center gap-1.5">
                              {base !== undefined
                                ? <><div className="h-2 rounded" style={{ width: `${(base / maxV) * 100}%`, minWidth: 3, background: BASELINE_COLOR }} /><span className="text-[9px] text-slate-500">{fmt(base)} baseline</span></>
                                : <span className="text-[9px] italic text-slate-600">new archetype — no baseline</span>}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Coins over time */}
                <HoverLineChart
                  title="Coins over time (mean per archetype)"
                  xLabels={report.strategies[activeStrats[0] ?? "A_Sprinter"]?.timeseries.t_minutes ?? []}
                  series={activeStrats.map((s) => ({
                    label: STRATEGY_LABEL[s], color: STRAT_COLOR[s],
                    points: report.strategies[s].timeseries.coins_mean,
                  }))}
                  yFmt={fmt}
                />

                {/* Graveyard */}
                <div className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-4">
                  <div className="mb-2 text-sm font-semibold text-slate-200">Unused Ingredients — the Graveyard (mean per run)</div>
                  <div className="space-y-1.5">
                    {activeStrats.map((s) => {
                      const m = report.strategies[s].summary_mean;
                      const maxV = Math.max(1, ...activeStrats.map((x) => report.strategies[x].summary_mean.graveyard_units));
                      const top = report.strategies[s].graveyard_top[0];
                      return (
                        <div key={s} className="flex items-center gap-2">
                          <span className="w-28 shrink-0 truncate text-[10px]" style={{ color: STRAT_COLOR[s] }}>{STRATEGY_LABEL[s]}</span>
                          <div className="h-3 flex-1 rounded bg-slate-800/70">
                            <div className="h-3 rounded bg-rose-500/70" style={{ width: `${(m.graveyard_units / maxV) * 100}%`, minWidth: 3 }} />
                          </div>
                          <span className="w-44 shrink-0 text-right text-[10px] text-slate-400">
                            {fmt(m.graveyard_units)}{top ? ` · worst: ${top.ingredient} ×${fmt(top.unused_mean)}` : ""}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Diagnosis */}
                <div>
                  <div className="mb-2 text-sm font-semibold text-slate-200">Dynamic Bottleneck Diagnosis</div>
                  <div className="grid gap-3 sm:grid-cols-2">
                    {activeStrats.map((s) => {
                      const d = report.strategies[s].diagnosis;
                      const m = report.strategies[s].summary_mean;
                      return (
                        <div key={s} className="rounded-xl border border-slate-700/70 bg-slate-900/50 p-3.5">
                          <div className="mb-1.5 flex items-baseline justify-between">
                            <span className="font-semibold" style={{ color: STRAT_COLOR[s] }}>{STRATEGY_LABEL[s]}</span>
                            <span className="text-[10px] text-slate-500">
                              ×{m.gax_avg_sale_mult} sale mult · {Math.round(m.mastered_recipes)} mastered · {m.regions_unlocked} regions
                            </span>
                          </div>
                          <div className="mb-1.5 flex flex-wrap gap-1.5">
                            {d.flags.length === 0
                              ? <span className="rounded bg-green-900/30 px-1.5 py-0.5 text-[11px] font-semibold text-green-300">✓ healthy</span>
                              : d.flags.map((f) => <span key={f} className="rounded bg-red-900/40 px-1.5 py-0.5 text-[11px] font-semibold text-red-300">{f}</span>)}
                          </div>
                          {d.notes.map((note, i) => <p key={i} className="mt-1 text-xs leading-relaxed text-slate-400">{note}</p>)}
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}
          </>
        )}

        <footer className="mt-10 border-t border-slate-800 pt-4 text-xs text-slate-500">
          Simulation runs in <code className="text-slate-400">scripts/simulate.worker.ts</code> importing the game's exact engine math
          (engine/gax via createGaxMath, engine/formulas, data/regions, data/masteryTrees) · legacy CLI baseline: <code className="text-slate-400">scripts/simulate.ts</code>.
        </footer>
      </div>
    </div>
  );
}
